### ISSUE TITLE
Loose strong dependencies

### ISSUE THREAD

**Issue by prokaktus** [valohai/django-allauth-2fa#10]
Currenty almost all dependencies in `setup.py` are exact. Is this really required?

```
"qrcode==5.1",
 "django-allauth==0.23.0",
"django-otp==0.3.1",
```

Python package version resolving not nearly as good as npm, unfortunately.

**Comment by clokep** [comment]
It isn't required, no. We should definitely make these more flexible.

**Comment by clokep** [comment]
I've changed this to >= in a recent commit. There's a couple other things I want to do and then we'll push a release to pypi.

**Comment by prokaktus** [comment]
@clokep thanks! Yes, release is the must thing.

**Comment by clokep** [comment]
@prokaktus FYI I just pushed a release, see #15.
