### ISSUE TITLE
two_factor/remove - StaticDevice matching query does not exist.

### ISSUE THREAD

**Issue by vocationeers** [valohai/django-allauth-2fa#100]
Maybe I am misunderstanding parts of django-allauth-2fa, but I encountered the bug above when trying to remove my two factor devices via the remove form.

The function seems to work fine if I have both, a TOTP device AND backup tokens. However, if no backup tokens were created ever "static_device = self.user.staticdevice_set.get(name='backup')" fails with a "DoesNotExist" exception and the tokens remain.

So the "Delete any backup tokens" section of TOTPDeviceRemoveForm has to be protected by a try/except clause that ignores backuptokens if none are present. Therefore I propose the following change:

```
class TOTPDeviceRemoveForm(forms.Form):
    def __init__(self, user, **kwargs):
        super(TOTPDeviceRemoveForm, self).__init__(**kwargs)
        self.user = user

    def save(self):
        # Delete any backup tokens.
        try:
            static_device = self.user.staticdevice_set.get(name='backup')
            static_device.token_set.all().delete()
            static_device.delete()
        except django_otp.plugins.otp_static.models.StaticDevice.DoesNotExist:
            pass

        # Delete TOTP device.
        device = TOTPDevice.objects.get(user=self.user)
        device.delete() 
```

**Comment by clokep** [comment]
@vocationeers Any chance you'd be willing to make a pull request with tests? That sounds reasonable to me.
