### ISSUE TITLE
unexpected behaviour of accounts/two_factor/setup/ -> page reload after pressing 'verify' 

### ISSUE THREAD

**Issue by Danane84** [valohai/django-allauth-2fa#101]
I am trying to use django-allauth & django-allauth-2fa in my Django app.  

My django-allauth app is set uo correctly - everything is working as expected. 

However, when trying to set up django-allauth-2fa I ran into some issues: Configuring a two-factor authentification at  `accounts/two_factor/setup/` when I scan the QR code, input the token generated and press _verify_ the page simply reloads with a new QR code instead of leading me to the next step in the Two-Factor configuration workflow. I can't figure out what my mistake may be, as I set up everything as written in the django-allauth-2fa documentation

My `Pipfile`: 
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "==3.0.0"
pylint = "==2.4.4"
django-crispy-forms = "==1.9"
django-allauth = "==0.42.0"
django-allauth-2fa = "==0.8"

[requires]
python_version = "3.7"
```

my `settings.py` file
```
...

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Local
    'users.apps.UsersConfig',
    'pages.apps.PagesConfig',

    #Third-party
    'allauth',
    'allauth.account',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'allauth_2fa',
    'crispy_forms',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth_2fa.middleware.AllauthTwoFactorMiddleware',
]

SITE_ID = 1

ACCOUNT_ADAPTER = 'allauth_2fa.adapter.OTPAdapter'

...
```

my` urls.py` file
```
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth_2fa.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
]
```

And I also ran `python manage.py migrate`

**Comment by clokep** [comment]
My guess would be that the included form isn't working for some reason. Do you do something weird with CSRF tokens? Are you overriding the template?

**Comment by Danane84** [comment]
The only two places where I am using CSRF tokens are in my login.html and logout.html files. 

login.html:
```
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="card">

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group mb-0 text-center">
        <button class="btn btn-primary" type="submit">Log In</button>
        </div>
    </form>

</div>
{% endblock content %}
```

logout.html:
```
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="card-body p-4">
                                
    <div class="text-center w-75 m-auto">
        <h4 class="text-dark-50 text-center mt-3 font-weight-bold">Hi {{ user.email }}!</h4>
        <p class="text-muted mb-4">Are you sure you want to sign out?</p>
    </div>

    <div class="container">
        <form method="post" action="{% url 'account_logout' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group mb-0 text-center">
                <button class="btn btn-danger" type="submit">Log Out</button>
            </div>
        </form>
    </div>
    
</div>
  
{% endblock content %}
```

**Comment by clokep** [comment]
I meant the templates that allauth-2fa uses.

Although now that I'm looking at the view again, this most likely occurs if you enter the wrong information. Do the clocks on the computer that is running your Django app and your TOTP devices match?

**Comment by Danane84** [comment]
My computer is 1min 25 sec behind my TOTP device (iPhone). But could this be the issue? It might always be the case that the TOTP device of at least one of the users of the app is slighty off compared to the time of the server. 

I also tried to set the `TIME_ZONE` in my settings.py from `'UTC'` to `'Europe/Vienna'` but it did not solve the issue

**Comment by clokep** [comment]
> My computer is 1min 25 sec behind my TOTP device (iPhone). But could this be the issue?

Yes, TOTP codes are valid for 30 seconds only.

It seems like django-otp has some configuration options for this though: https://github.com/django-otp/django-otp/blob/master/docs/source/overview.rst#totp-devices

**Comment by Danane84** [comment]
Indeed, syncing the clocks of my TOTP device and my computer solved the problem. Many thanks for your guidance!

**Comment by clokep** [comment]
Seems like we should be showing an error on the form if the TOTP code is wrong though. 😢
