### ISSUE TITLE
redirect_field_name is not passed to django-allauth-2fa

### ISSUE THREAD

**Issue by falc410** [valohai/django-allauth-2fa#105]
When using django-allauth and django-allauth-2fa the redirect_field_name is not passed to the 2fa login page. As you can see from the debug logs, first there is a POST to /accounts/login where the password of the user is checked and then, if required (based on BaseRequire2FAMiddleware) a GET to the two-factor-authenticate is executed - however the redirect_field_name value is gone. 

Yes this is more of a problem with django-allauth but I was expecting a seamless integration. Any ideas what can be done? Right now I have my own adapter (inherited from allauth_2fa.adapter.OTPAdapter) where I can call get_login_redirect_url, however since the redirect_field value is gone, I have no way to build any logic as to where to redirect the user to. 

> [11/Oct/2020 12:14:35] INFO [django.server:154] "GET /admin/ HTTP/1.1" 302 0
> [11/Oct/2020 12:14:35] INFO [django.server:154] "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
> [11/Oct/2020 12:14:35] INFO [django.server:154] "GET /accounts/login?next=/admin/login/%3Fnext%3D/admin/ HTTP/1.1" 301 0
> [11/Oct/2020 12:14:35] INFO [django.server:154] "GET /accounts/login/?next=/admin/login/%3Fnext%3D/admin/ HTTP/1.1" 200 23174
> [11/Oct/2020 12:14:38] INFO [django.server:154] "POST /accounts/login/ HTTP/1.1" 302 0
> [11/Oct/2020 12:14:38] INFO [django.server:154] "GET /two-factor-authenticate HTTP/1.1" 200 21569
> [11/Oct/2020 12:14:43] INFO [django.server:154] "POST /two-factor-authenticate HTTP/1.1" 302 0
> [11/Oct/2020 12:14:43] INFO [django.server:154] "GET / HTTP/1.1" 301 0

**Comment by sabipu** [comment]
Following this issue. I would have thought there would be a seamless integration as allauth_2fa is built on top of all_auth. Can authors of the plugin please have a look at this a suggest?

**Comment by 9mido** [comment]
Maybe these could help someone make a PR:

https://stackoverflow.com/questions/58357047/how-to-properly-redirect-from-one-app-to-another-app-in-django

https://stackoverflow.com/questions/31334460/urls-py-redirect-the-page-to-another-app

https://stackoverflow.com/questions/53430519/django-redirect-from-one-app-to-another-apps-page-django

https://stackoverflow.com/questions/28554335/django-redirect-to-a-view-outside-the-app

@falc410 Can you share with us your adapter method where you call get_login_redirect_url? 

I see in the django-allauth views.py file has multiple redirect_field_name fields. It seems like the LoginView class of django-allauth may need to change or django-allauth-2fa may need to change to address this (not sure).

When you say you are using BaseRequire2FAMiddleware, is this problem only occurring when using BaseRequire2FAMiddleware as opposed to not using it? Are you doing what the docs say in regards to this BaseRequire2FAMiddleware middleware or are you doing something else? Can you share? 

https://django-allauth-2fa.readthedocs.io/en/latest/advanced/#forcing-a-user-to-use-2fa

Correct me if I am wrong, but isn't this issue the same as what PR https://github.com/percipient/django-allauth-2fa/pull/99 claims to solve?

Couldn't we use `request.GET.next` to get what the next value is to ensure that it gets redirected there?

**Comment by akx** [comment]
This should have been fixed by #131.
