### ISSUE TITLE
TypeError at /account/two-factor-authenticate - exists again in 0.9

### ISSUE THREAD

**Issue by nhondong** [valohai/django-allauth-2fa#132]
Hi, 

This issue exists again in the latest 0.9rc1:

https://github.com/valohai/django-allauth-2fa/pull/42

After entering OTP Token, you get the Error:
TypeError at /account/two-factor-authenticate

super(type, obj): obj must be an instance or subtype of type

**Comment by akx** [comment]
Are you using a custom adapter? Could you show the code for it?

**Comment by akx** [comment]
Closing for now since there was no feedback on this.

Please let us know if this is still an issue.
