### ISSUE TITLE
Join jazzband?

### ISSUE THREAD

**Issue by valberg** [valohai/django-allauth-2fa#133]
I was thinking that maybe the project could benefit from joining Jazzband (https://jazzband.co)? What do you thing @akx ?

**Comment by valberg** [comment]
Ping @akx :)

**Comment by valberg** [comment]
Cool! Should I start the process over in https://github.com/jazzband/help/issues?

**Comment by matmair** [comment]
Hi there @valberg and @akx  - any movement on this?

**Comment by jkaeske** [comment]
Are there any news on this? @valberg did you create the issue in the jazzband repo?

**Comment by valberg** [comment]
@jkaeske I did not - I have been waiting for an answer from @akx. We can start the process, but we need the Valohai people to approve it.

**Comment by jkaeske** [comment]
I see, then we probably have to wait for @akx or @ruksi to give input here.
I could prepare the issue for jazzband if it is a problem of time to make the request.

Since allauth is a key package for a lot of application, I think it would be sad to leave this repo unmaintained to be honest.

**Comment by akx** [comment]
I'm sorry I dropped the ball on this!

To be frank, I'm maybe a bit hesitant on Jazzband, considering [they too seem to have a lot on their plates](https://github.com/jazzband/help/issues/196), and having a large group of people managing (i.e. being able to e.g. upload releases of) a security-critical library such as this sounds a bit iffy.

**Comment by valberg** [comment]
It is only the people who are appointed maintainers of a project who are able to publish new versions PyPI.

But if you wish to keep the repo under Valohai that is fine by me ☺️ I only suggested it to keep the ball rolling. So as long as we can keep said ball rolling it doesn't matter to me what organisation the project is under 😉

**Comment by jkaeske** [comment]
> I'm sorry I dropped the ball on this!
> 
> To be frank, I'm maybe a bit hesitant on Jazzband, considering [they too seem to have a lot on their plates](https://github.com/jazzband/help/issues/196), and having a large group of people managing (i.e. being able to e.g. upload releases of) a security-critical library such as this sounds a bit iffy.

That is for sure a good point.
How could we help you to push things in the right direction?
Can we help planning for a future 1.0 release or what would help you?

**Comment by pennersr** [comment]
> I'm sorry I dropped the ball on this!
> 
> To be frank, I'm maybe a bit hesitant on Jazzband, considering [they too seem to have a lot on their plates](https://github.com/jazzband/help/issues/196), and having a large group of people managing (i.e. being able to e.g. upload releases of) a security-critical library such as this sounds a bit iffy.

FWIW, there was a similar discussion over at django-allauth: https://github.com/pennersr/django-allauth/issues/3202#issuecomment-1367149461

**Comment by valberg** [comment]
I believe a decision has been made, so I'm closing this issue. If anyone has an objection just say the word - although I think it has to be some very convincing arguments.
