### ISSUE TITLE
Configurable redirect URLs

### ISSUE THREAD

**Issue by SchrodingersGat** [valohai/django-allauth-2fa#142]
I would like to be able to redirect the user to a custom URL after removing 2FA from their account:

Would you guys be happy with allowing the success URL of this view to be customizable?

https://github.com/valohai/django-allauth-2fa/blob/84ee2bfbc1979967219248b6ffd0858600ba3e9d/allauth_2fa/views.py#L142

Currently we get around this with a custom view.

**Comment by valberg** [comment]
@SchrodingersGat Seems like a fair thing to be able to customize - although it is doable by overriding the view. Ie.:

```
class CustomTwoFactorRemove(TwoFactorRemove):
    def get_success_url(self):
        return "<custom url>"
```

**Comment by valberg** [comment]
@SchrodingersGat Sounds like a fair thing to be able to customize.
