### ISSUE TITLE
Release onto pypi

### ISSUE THREAD

**Issue by clokep** [valohai/django-allauth-2fa#15]
I've wanted to do a release, but this has depended on a few things. Tracking this here.
- [x] Add a license #14 
- [x] Add tests #4 
- [x] Configure CI #5 
- [x] Test across multiple environments #11
- [x] Add a changelog / refresh the README #13
- [x] Register on pypi (this is a done at https://pypi.python.org/pypi/django-allauth-2fa/)

**Comment by clokep** [comment]
I think this is all that is left. @dicato please weigh in if there's something else!

**Comment by dicato** [comment]
👍 I think it looks great!

**Comment by clokep** [comment]
Just pushed version 0.2!

https://pypi.python.org/pypi/django-allauth-2fa/0.2

`pip install django-allauth-2fa==0.2`
