### ISSUE TITLE
Success social login directing to failed social login page

### ISSUE THREAD

**Issue by avmturo** [valohai/django-allauth-2fa#160]
I am working with the latest release, not off the main branch. I originally ran into this issue : [This issue](https://github.com/valohai/django-allauth-2fa/issues/143), which I have gone around by writing my own adapter and redefining login as such: 

```
def login(self, request, user):
        # Require two-factor authentication if it has been configured.
        if self.has_2fa_enabled(user):
            # Cast to string for the case when this is not a JSON serializable
            # object, e.g. a UUID.
            request.session["allauth_2fa_user_id"] = str(user.id)

            redirect_url = reverse("two-factor-authenticate")
            # Add "next" parameter to the URL.
            if hasattr(request.resolver_match.func, 'view_class'):
                # The view is a class-based view
                view = request.resolver_match.func.view_class
                view.request = request
                success_url = view.get_success_url()
            else:
                # The view is a function-based view
                view = request.resolver_match.func
                success_url = reverse(view)
            query_params = request.GET.copy()
            if success_url:
                query_params['next'] = success_url
            if query_params:
                redirect_url = '{}?{}'.format(redirect_url, urlencode(query_params))

            raise ImmediateHttpResponse(response=HttpResponseRedirect(redirect_url))

        # Otherwise defer to the original allauth adapter.
        return super().login(request, user)
```

Now the social login "works" mostly, only remaining issue I'm having is even though the login with social account and 2fa works, it directs to this page. 
"accounts/google/login/callback"
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/30347978/233075212-88e702d6-8ed1-42c2-9c1a-4dcc47c1e799.png">

If I navigate back to "/" from here the social account is logged in. 

I can keep digging, but wondering if it's something obvious I'm missing, or if it's better to just fork main and use it instead of the last release:
https://pypi.org/project/django-allauth-2fa/ 0.10.0

**Comment by valberg** [comment]
What was the issue?

**Comment by avmturo** [comment]
Couldn't quite figure it out yet, but have run into some more issues I'm addressing. Didn't wan't to bother you with this until I make sure it is the only issue remaining, as I'll be doing some refactoring.
