### ISSUE TITLE
Missing dependabot config

### ISSUE THREAD

**Issue by valberg** [valohai/django-allauth-2fa#180]
@akx Shouldn't we have a `dependabot.yml` config? For some reason it is not there, and we have some dependencies which are in need of an update (for instance in requirements-dev.txt)

**Comment by akx** [comment]
In _need_ of update? 😁 

I think `requirements-dev.txt` should probably just be nuked altogether – we shouldn't prescribe `django-extensions` or `ipdb` (esp. since `pdbpp` is a thing and so on).

**Comment by valberg** [comment]
I'm doing a PR where we get test deps and such into pyproject.toml, will cleanup stuff as well - stay tuned.

**Comment by akx** [comment]
Moved to pyproject.toml in #181.
