### ISSUE TITLE
When using with the latest version of django-allauth, 2FA is bypassed 

### ISSUE THREAD

**Issue by apagano-vue** [valohai/django-allauth-2fa#186]
We've just tested compatibility of django-allauth-2fa (0.11.1) with the latest version of django-allauth (0.56.0). 

When using those two versions together, 2FA authentication is silently bypassed and the user can connect just using their credentials. 

The regression seems to have been introduced between 0.54.0 and 0.56.0 (perhaps something to do with the new required [allauth.account.middleware.AccountMiddleware](https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst#backwards-incompatible-changes)) 

I'd be happy to look more into it if there is interest in making django-allauth-2fa compatible with the latest version of django-allauth

**Comment by pennersr** [comment]
Confirmative -- this is an issue in django-allauth. You can expect a 0.56.1 that fixes this.

**Comment by pennersr** [comment]
Done -- please upgrade to 0.56.1.

**Comment by pennersr** [comment]
@apagano-vue Can you please close this issue?

**Comment by akx** [comment]
@pennersr Should 0.56.0 be yanked from PyPI?

**Comment by pennersr** [comment]
Yes :white_check_mark:
