### ISSUE TITLE
Clean-up URLs

### ISSUE THREAD

**Issue by clokep** [valohai/django-allauth-2fa#29]
The URLs we include are kind of a mess:
- Some use dashes, others underscores
- None of them have a trailing slash
- Some are sub-directories, others are not

Theoretically we can just change these if people use names, but we would probably want to include redirects. It could also be nice to use a namespace.

**Comment by 9mido** [comment]
Wouldn't following this be able to help with the redirecting apsect?

https://stackoverflow.com/questions/14959217/django-url-redirect

https://stackoverflow.com/questions/15706489/redirect-to-named-url-pattern-directly-from-urls-py-in-django

**Comment by akx** [comment]
1.0 should just drop the "old" URLs (that don't have trailing slashes).

**Comment by valberg** [comment]
> 1.0 should just drop the "old" URLs (that don't have trailing slashes).

Oh yes please!
