### ISSUE TITLE
Deactivating 2FA should require 2FA authentication

### ISSUE THREAD

**Issue by clokep** [valohai/django-allauth-2fa#30]
It's fairly standard practice that deactivating 2FA requires you to re-authenticate with 2FA. This is related to #7.

**Comment by adrijanb** [comment]
Something new on here? That would be a nice feature!

**Comment by zsh-lgtm** [comment]
The lack of 2FA requirement for disabling 2FA creates a vulnerability here.


It's outlined further here in OWASP's 2FA guidelines: 

https://cheatsheetseries.owasp.org/cheatsheets/Multifactor_Authentication_Cheat_Sheet.html#when-to-require-mfa
