### ISSUE TITLE
Exception when url has no name

### ISSUE THREAD

**Issue by MightySCollins** [valohai/django-allauth-2fa#37]
When a URL has no name the following exception is thrown:
`AttributeError: 'NoneType' object has no attribute 'startswith'`
`File "/usr/local/lib/python3.5/site-packages/allauth_2fa/middleware.py", line 18, in process_request`

``` python
def process_request(self, request):
        if not resolve(request.path).url_name.startswith( # This does not always exist
                'two-factor-authenticate'):
            try:
                del request.session['allauth_2fa_user_id']
            except KeyError:
                pass
```

If I get time I'll make a PR. I could just add a name but an exception like this should not be thrown by a package.

**Comment by clokep** [comment]
Oops. That's definitely a problem!

**Comment by clokep** [comment]
I put up PR #38 to fix this. If you have a moment to look over it and make sure it seems sane, that would be appreciated! 👍
