### ISSUE TITLE
next url parameter is lost when going through 2fa

### ISSUE THREAD

**Issue by ssimono** [valohai/django-allauth-2fa#51]
When I attempt to visit a page that requires authentication, I get redirected to the login form with a next parameter (e.g `/login/?next/my/path`). But when 2FA is enabled, this next redirect parameter is lost and I end up in the default account page.

The PR #44 seems to make sure that when I visit `/two-factor-authenticate?next=/my/path` then the query parameter is passed correctly.

But I think there is still a problem before: when submitting the first user/password form, the next parameter might be passed with a POST parameter, and when this happens the next path is lost. And the default template for allauth actually passes the next [as a POST parameter](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/login.html#L40), and not as a url query.

See attached screenshot, I end up in `accounts/profile` instead of my desired path

![screenshot from 2017-06-27 16-33-30](https://user-images.githubusercontent.com/2179169/27593161-b3e301ae-5b56-11e7-819c-7ffefdb7a04c.png)

I am running Django **1.11**, allauth **0.32** and allauth-2fa **0.4.4**

**Comment by ssimono** [comment]
FYI I went around this problem by overriding the default allauth login template with something like this

```html
<form class="login" method="POST" action="{% url 'account_login' %}{% if redirect_field_value %}?{{ redirect_field_name }}={{ redirect_field_value }}{% endif %}">
```

so the form's `action` attribute takes next parameter into account. But maybe allauth-2fa could benefit from handling the next parameter with POST as well

**Comment by clokep** [comment]
Our login form looks something like this:

```jinja
<form class="login" method="POST" action="{% url 'account_login' %}?{{ request.GET.urlencode }}">
  {% csrf_token %}
  {% bootstrap_form form layout='placeholder' %}
  {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <button class="btn btn-info btn-block" type="submit">Log In</button>
</form>
```

(Note that this uses [django-bootstrap3](http://django-bootstrap3.readthedocs.org/), but those just render to standard HTML fields.)

It looks like we're passing forward the `next` parameter by passing it in as part of `request.GET.urlencode`? Ideally this would work with the standard allauth template/form too!

Thanks for identifying the problem so succinctly, any idea how allauth handles this parameter that passed in / what the fix would be?

**Comment by ssimono** [comment]
Hello,

So in the form you posted, I see that you pass the `next` parameter with GET and POST at the same time. GET with `request.GET.urlencode` and POST with the hidden input. And allauth-2fa only handles GET but it is fine in your case.

I looked into [allauth source](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L63) and after going [several layers deep](https://github.com/pennersr/django-allauth/blob/master/allauth/utils.py#L299) I found that it takes the POST parameter and defaults to the GET parameter if not found.

So I would say that the fix for allauth-2fa would be to add this field in the authenticate form and in the authenticate template, so it gets passed to allauth if provided. I might actually try to make a PR at some point

**Comment by clokep** [comment]
@ssimono A pull request would be appreciated! Let me know if you have any questions or need guidance. 👍

**Comment by akx** [comment]
This can be a little tricky. The way we get to `OTPAdapter.login()` is through here: https://github.com/pennersr/django-allauth/blob/bd1d4a83b2490b7929310f9301ae8a1d4db7d54a/allauth/account/utils.py#L149-L150

The actual `redirect_url`, whether it's been obtained from POST, GET or static configuration, is not directly passed to the adapter... There are two ways to try to acquire it, both of which are dirty in their own ways:

1. Walk up the call stack using `sys.getframe()` or similar to find the bottom-most `redirect_url` string (it should be only one frame higher than the adapter)
2. Assume everyone uses `next` as their redirect URL parameter/POST field name and look them up in `self.request` in the adapter.

I'd personally prefer option 1.

**Comment by ErwinJunge** [comment]
I think I've written up a standards-compliant way of fixing this for GET and POST. Tests included. See accompanying PR. It uses the pre-existing methods for getting the success_url from the view class, after getting that from the request.
