### ISSUE TITLE
Allow issuer for QR code to be customizable

### ISSUE THREAD

**Issue by melinath** [valohai/django-allauth-2fa#53]
Currently, the issuer for the qr code is hardcoded as part of the qr code generator view and always is the current django Site for the current request. https://github.com/percipient/django-allauth-2fa/blob/master/allauth_2fa/views.py#L206

If your site's 'name' is set some other way - for example if you're using Wagtail, which has its own site model - this is a problem, and there's not a good way to get around it without copying the entire qr generator view.

Proposed solution: add a `get_issuer` method to `QRCodeGeneratorView` that can be easily overridden to allow customization of the issuer name.

**Comment by clokep** [comment]
That seems reasonable! Do you know if that's that usually how frameworks deal with this?

It probably makes sense to not require the sites package anyway.

Would you be able to put up a PR making this change? Thanks!

**Comment by clokep** [comment]
Another thought, would it make sense to get this from the adapter some-how? I'm unsure if it's useful anywhere else though.

**Comment by melinath** [comment]
I think that if your intention is that all customization be done via the adapter, then it could make sense to put the customization hook there. I can't guarantee putting in a PR, especially since I'm no longer working on the project that uses this.
