### ISSUE TITLE
Accesing link "remove 2fa" when not strongly logged in

### ISSUE THREAD

**Issue by maxcanada** [valohai/django-allauth-2fa#6]
Hi, 

When logging in (having 2FA enabled), we are automatically directed on the authenticate page. Which is normal, but then if I try to click on the link to disable the 2FA, I got a 500 error AttributeError: 'AnonymousUser' object has no attribute 'totpdevice_set'

Can you reproduce the bug ?

Thanks

**Comment by dicato** [comment]
We will take a look! I also filed an issue to help us reproduce potential issues like this: #9

**Comment by clokep** [comment]
This was fixed in #31 and/or #27 (and in the newest release: `django-allauth-2fa==0.3.2`). Thanks for filing! 👍
