### ISSUE TITLE
Change QR Code generation to enable displaying the secret

### ISSUE THREAD

**Issue by dwasyl** [valohai/django-allauth-2fa#63]
In some cases, a user may not be able to take a picture of the QR code. In those cases, some sites display the secret for the user to enter manually into their Authentication app.

Based on the way this package generates the QR code, I suspect it will take some refactoring to make this possible.

**Comment by clokep** [comment]
How is the secret shown in this case?

I suspect you could override the `TwoFactorSetup` to include information about the device in the template, I don't think it would be too difficult to encode the key in a different way.

**Comment by dwasyl** [comment]
If you look at Github's 2FA setup screen on the page where you view the QR code there is a text link to a modal dialog that pops up with the text version of the secret that can be manually entered into an Authenticator app.

I'm not entirely sure of what change to make in this case - basically the secret that is used to generate the QR code needs to be shared with the context. Presumably it needs to be provided at the same time as the QR code is loaded, although that currently just returns an image.

**Comment by clokep** [comment]
You would likely want it returned in the context of the `TwoFactorSetup` view.

**Comment by akx** [comment]
As an aside, commit 94d12db8b5a6621613634e7d55420290de9df4f1 (in #74) makes it possible to access the secret from the view using the template variable `{{ view.device.key }}`.

**Comment by dwasyl** [comment]
Oh, that would be great - thanks for the heads up @akx. When that gets merged in, it will make life easier to do this. I'd taken  crack at it but got pulled away onto other projects as this was just a "nice to have" feature.

**Comment by dwasyl** [comment]
Closing because the noted changes made this possible and it's in the current release.
