### ISSUE TITLE
Select pages protected by 2FA

### ISSUE THREAD

**Issue by maxcanada** [valohai/django-allauth-2fa#7]
Hi, 
Is there currently a way to select the pages that are protected by the 2FA ? 
Thanks for your help :)

**Comment by dicato** [comment]
Meaning some views require the User to have 2FA configured?

**Comment by clokep** [comment]
There's currently no way to do that. You can easily select pages that require login. Could be a neat decorator/mixin to require 2FA though!

**Comment by clokep** [comment]
This was fixed in #31 and/or #27 (and in the newest release: `django-allauth-2fa==0.3.2`).
Thanks for filing! 👍 

**Edit:** Oops, that comment was for #6...too many browser tabs open.
