### ISSUE TITLE
How to get status

### ISSUE THREAD

**Issue by maxclax** [valohai/django-allauth-2fa#78]
I wanna know about status: active it or not for user . How can I get it?

**Comment by clokep** [comment]
Depending on what version you're using (...I probably need to do a release soon...) you can check how the access mixin does it:

https://github.com/percipient/django-allauth-2fa/blob/27f6c4cb5a1cf173d01d34ae28b75a77a96512dd/allauth_2fa/mixins.py#L8-L19

Essentially it just checks whether there are any valid 2FA tokens (and then assumes they were used to login):

https://github.com/percipient/django-allauth-2fa/blob/27f6c4cb5a1cf173d01d34ae28b75a77a96512dd/allauth_2fa/utils.py#L44-L46

**Comment by maxclax** [comment]
> Depending on what version you're using (...I probably need to do a release soon...) you can check how the access mixin does it:
> 
> [django-allauth-2fa/allauth_2fa/mixins.py](https://github.com/percipient/django-allauth-2fa/blob/27f6c4cb5a1cf173d01d34ae28b75a77a96512dd/allauth_2fa/mixins.py#L8-L19)
> 
> Lines 8 to 19 in [27f6c4c](/percipient/django-allauth-2fa/commit/27f6c4cb5a1cf173d01d34ae28b75a77a96512dd)
>  class ValidTOTPDeviceRequiredMixin(AccessMixin): 
>      no_valid_totp_device_url = reverse_lazy('two-factor-setup') 
>   
>      def dispatch(self, request, *args, **kwargs): 
>          if not request.user.is_authenticated: 
>              return self.handle_no_permission() 
>          if not user_has_valid_totp_device(request.user): 
>              return self.handle_missing_totp_device() 
>          return super(ValidTOTPDeviceRequiredMixin, self).dispatch(request, *args, **kwargs) 
>   
>      def handle_missing_totp_device(self): 
>          return HttpResponseRedirect(self.no_valid_totp_device_url) 
> 
> Essentially it just checks whether there are any valid 2FA tokens (and then assumes they were used to login):
> 
> [django-allauth-2fa/allauth_2fa/utils.py](https://github.com/percipient/django-allauth-2fa/blob/27f6c4cb5a1cf173d01d34ae28b75a77a96512dd/allauth_2fa/utils.py#L44-L46)
> 
> Lines 44 to 46 in [27f6c4c](/percipient/django-allauth-2fa/commit/27f6c4cb5a1cf173d01d34ae28b75a77a96512dd)
>  if not user.is_authenticated: 
>      return False 
>  return user.totpdevice_set.filter(confirmed=True).exists()

Thanks I added in user model this code
`
    def check_2fa(self):
        return self.totpdevice_set.filter(confirmed=True).exists()
`

**Comment by clokep** [comment]
Glad you got it working. I'm going to close this!
