### ISSUE TITLE
Redirect log out if not strongly authenticated

### ISSUE THREAD

**Issue by maxcanada** [valohai/django-allauth-2fa#8]
Hi,

While logged in but not yet input the 2FA code yet (so, on the authenticate page), when I try to access another URL, it directly logs me out. This is not a behavior that I want. I want to display the authenticate page again. Is there currently a way to do it ?

Thanks!

**Comment by clokep** [comment]
This matches the behavior of all the web apps that I checked. I don't have a strong opinion about this, but if you don't finish the login workflow, starting over seems like a reasonable compromise between code complexity and user experience.

**Comment by clokep** [comment]
I think this would be doable with a custom middleware layer that just redirects instead of logs out, which is what the new `AllauthTwoFactorMiddleware` does.

I'm inclined not to support this, but if you feel really strongly, please put up a PR with the appropriate changes and tests!
