### ISSUE TITLE
Release 0.6 missng 'two-factor-qr-code' reverse url

### ISSUE THREAD

**Issue by squio** [valohai/django-allauth-2fa#81]
A quick test to add django-allauth-2fa to an existing project didn't work because the view `two_factor/setup` breaks on the reverse lookup of 'two-factor-qr-code'.

Our project uses pip3 with a requirements.txt file for deployment so there is no easy way to use a non-release version of the code.

Using Python 3.7.3

Relevant parts of requirements.txt:
```
Django~=2.2
django-allauth~=0.39
django-allauth-2fa~=0.6
```

The error message:
```
Request Method: | GET http://localhost/accounts/two_factor/setup
Django Version: 2.2.3
Exception: NoReverseMatch
Reverse for 'two-factor-qr-code' not found. 'two-factor-qr-code' is not a valid view function or pattern name.
/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 668
```
It appears there are quite a few commits since the last 0.6 release which may fix thi issue already.

What is the timeline for a new release?

**Comment by clokep** [comment]
Hm...we're using 0.6 and this isn't cause us issues. Did you add the 2FA URLs to your root URL configuration? The "latest" docs on read the docs might be wrong, check out the [installation guide](https://django-allauth-2fa.readthedocs.io/en/0.6/installation/).

> Our project uses pip3 with a requirements.txt file for deployment so there is no easy way to use a non-release version of the code.

Not really a solution, but it is possible to do this using git URLs, see https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support We do that for a few of our requirements... (if you do this, I recommend using a specific commit hash or tag).

> It appears there are quite a few commits since the last 0.6 release which may fix thi issue already.

I believe that URL no longer exists in `master`!

> What is the timeline for a new release?

There's no particular timeline, I was hoping to finish the two outstanding PRs before releasing, but they've been sitting there for a while now.

**Comment by squio** [comment]
Indeed, my bad; we have allauth included at prefix `'accounts/'` in a separate file `my_app.site_urls` and so configured 2fa similarly:
```
    path('accounts/', include('allauth_2fa.urls')),
```
The prefix wasn't the problem but the urls *must* be included in the `urls.py` file which is configured in `settings.py` it appears.

With that change it works for me.
Thanks!

**Comment by clokep** [comment]
@squio My guess would be that you have a namespace set in `my_app.site_urls`, which is why that wouldn't work.

Glad you figured it out though! 👍
