### ISSUE TITLE
Using Email for Demo without TOTP

### ISSUE THREAD

**Issue by Cabalist** [valohai/django-allauth-2fa#83]
I am getting a crash when trying to use the `otp_email` by itself.

It appears the code calls  `allauth_2fa.utils.user_has_valid_totp_device()` without checking to see which device(s) are installed.   Since in our demo app we just have     'django_otp.plugins.otp_email', and none of the others devices installed we get the following error `relation "django_otp_totpdevice" does not exist`

Adding `'django_otp.plugins.otp_totp',` to the INSTALLED_APP fixes this issue but then pushes the user through the TOTP flow instead of using email.

Given that there are other devices in the django_otp ecosystem (HOTP, Static, etc) it might be worthwhile to have `user_has_valid_totp_device()` replaced by something more generic `user_has_valid_device` with some logic to detect the install apps.

**Comment by clokep** [comment]
This seems related to #23. The current code has some assumptions that TOTP wants to be enabled. If you can figure out a good way to generalize this, I'd be happy to include any changes!
