### ISSUE TITLE
Support Django 3.0 (/ drop support for Python 2.7)

### ISSUE THREAD

**Issue by hailkomputer** [valohai/django-allauth-2fa#84]
Hi, I am currently evaluating upgrading a project to Django 3 and allauth-2fa is incompatible because dropped support of django.utils.six in version 3.

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

Here is a traceback of running allauth-2fa with Django 3.

```
|   File "/usr/local/lib/python3.7/site-packages/allauth_2fa/utils.py", line 8, in <module>
|     from django.utils.six import BytesIO
| ModuleNotFoundError: No module named 'django.utils.six'
```

Any plans to migrate to [six](https://pypi.org/project/six/) and give support to Django 3?

Thank you

**Comment by clokep** [comment]
It is on my todo list to drop support for Python 2 at some point across a few projects. I don't think I'll get to it soon though, so any help would be appreciated. It is rather unfortunate that both Django 1.11 and Django 3 are currently "supported" but code can't be written to support both of them (while supporting Python 2 and Python 3). 👎

**Comment by dmptrluke** [comment]
Can we have a release with this change in place?

**Comment by gtaylor** [comment]
Before I take the hacksaw out and start lopping: will small PRs that shed Python 2.x cruft be accepted? Probably not going to be pragmatic for me to do the Python 2.x removal in one mega PR.

**Comment by clokep** [comment]
@gtaylor Thanks for commenting. I believe this work was done in #86 and I failed to close this issue!

I haven't had time yet to do a release with the changes however.
