### ISSUE TITLE
Get a release out with Django 3.0 support?

### ISSUE THREAD

**Issue by valberg** [valohai/django-allauth-2fa#92]
Hi!

I was thinking if we shouldn't get a release out of django-allauth-2fa that supports django 3.0?

If I can do anything just say the word :)

Cheers!

**Comment by clokep** [comment]
I'll do this today.

**Comment by clokep** [comment]
I just pushed 0.8 with support for Django 3.0.

See the full changelog: https://github.com/percipient/django-allauth-2fa/blob/master/CHANGELOG.rst#08-february-3-2020

**Comment by valberg** [comment]
@clokep Awesome work! :+1:

**Comment by clokep** [comment]
Thanks, sorry for the delay on this!

**Comment by valberg** [comment]
@clokep Nothing to be sorry about! :)
